# Generated by Django 6.0.2 on 2026-02-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('DIVIDEND', 'Dividend'), ('SPLIT', 'Split'), ('RIGHTS ISSUE', 'Rights Issue'), ('AGM', 'AGM'), ('BONUS ISSUE', 'Bonus Issue'), ('EARNINGS', 'Earnings')], max_length=50)),
                ('event_date', models.DateField()),
                ('desciption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
