# Generated by Django 6.0.2 on 2026-02-20 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockevent',
            options={'ordering': ['announcement_date']},
        ),
        migrations.RenameField(
            model_name='stockevent',
            old_name='event_date',
            new_name='announcement_date',
        ),
        migrations.RemoveField(
            model_name='stockevent',
            name='desciption',
        ),
        migrations.CreateModel(
            name='BonusIssueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_ratio', models.CharField(max_length=10)),
                ('xd_date', models.DateField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_details', to='events.stockevent')),
            ],
        ),
        migrations.CreateModel(
            name='DividendEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_type', models.CharField(choices=[('CASH', 'Cash Dividend'), ('SCRIP', 'Scrip Dividend')], max_length=10)),
                ('xd_date', models.DateField()),
                ('dividend_per_share', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('scrip_ratio', models.CharField(blank=True, max_length=6, null=True)),
                ('payment_date', models.DateField()),
                ('desciption', models.TextField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_details', to='events.stockevent')),
            ],
        ),
        migrations.CreateModel(
            name='EarningsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_period', models.CharField(max_length=10)),
                ('report_date', models.DateField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_details', to='events.stockevent')),
            ],
        ),
        migrations.CreateModel(
            name='RightsIssueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xr_date', models.DateField()),
                ('rights_ratio', models.CharField(max_length=20)),
                ('subscription_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trade_start_date', models.DateField()),
                ('trade_close_date', models.DateField()),
                ('last_payment_date', models.DateField()),
                ('desciption', models.TextField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rights_details', to='events.stockevent')),
            ],
        ),
        migrations.CreateModel(
            name='SplitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_ratio', models.CharField(max_length=10)),
                ('xd_date', models.DateField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='split_details', to='events.stockevent')),
            ],
        ),
    ]
