# Generated by Django 6.0.2 on 2026-02-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_stockevent_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dividendevent',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='rightsissueevent',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='bonusissueevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='splitevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
