# Generated by Django 6.0.2 on 2026-02-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_desciption_dividendevent_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockevent',
            index=models.Index(fields=['announcement_date'], name='events_stoc_announc_d149fb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockevent',
            index=models.Index(fields=['stock_symbol', 'announcement_date'], name='events_stoc_stock_s_30650e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockevent',
            index=models.Index(fields=['event_type', 'announcement_date'], name='events_stoc_event_t_2fad19_idx'),
        ),
    ]
